(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];Get["Packages\\TextbookFigurePreamble.wl"] (* loads libraries, textbook stylings and defines txbExport *)


(* ::Input::Initialization:: *)
jFont[n_]:= Directive[FontSize->n,FontFamily->jStyle["FontFamily"]];
Ch8DCApparatus := Module[{},
appcolour = LightGray;
fieldColour = jStyle["ParastichyColour"][1];
dropColour = jStyle["ParastichyColour"][2];
diskThickness = 1;
dropRadius = 0.4;
disk = {FaceForm[appcolour],Cylinder[{{0,0,0},{0,0,diskThickness}},10]};
dropper  = {FaceForm[appcolour],Tube[{{0,0,16},{0,0,20},{10,10,20},{10,10,0}},.5]};
airDrops = {dropColour,Map[Sphere[{0,0,#},dropRadius]&,{12,8,4}]};
airField = {fieldColour,Arrow[{{1,0,14},{1,0,6}}]};
airTime = {Arrowheads[{-Automatic,Automatic}],Arrow[{{1,0,12},{1,0,8}}]};
arrow[angle_] := Module[ {cs},cs={Cos[angle],Sin[angle]}; Arrow[ {Append[cs * 1,diskThickness*1.5],Append[cs*8,diskThickness*1.5]}]];
diskarrows = {fieldColour,Map[arrow,(10+ Subdivide[ 0, 360, 6]) Degree]};
diskPoint[angle_,r_] := Module[{cs},cs={Cos[angle],Sin[angle]}; Sphere[  Append[r *cs,diskThickness+dropRadius/2],dropRadius]];
diskPattern[angle_,rise_,n_] := Table[  diskPoint[ i * angle-20  Degree , i * rise ],{i,n}];
diskDrops = {dropColour,diskPattern[(180) Degree, 1.5,6]};

Graphics3D[{
{Lighter[dropColour],Cuboid[{-11,-11,0},{11,11,0.1}]},
disk,dropper,airDrops,airTime,diskarrows,diskDrops,
,
Style[Text["Charged ferrofluid drops",{0,0,14}],jFont[12]]
,Style[Text["Inter-drop time",{5,1,11}],jFont[12]]
,Style[Text["Centrifugal\nvelocity",{5,3,diskThickness *2 }],Directive[fieldColour,jFont[12],LineSpacing->{0, 6}]]
}
,Lighting->"Neutral",Boxed->False]
];



